### ISSUE TITLE
COMPLIANCE: pip install

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#70]
```
#    Python pip install
- name: add psycopg2 for PostgreSQL
  pip:
    name: psycopg2
```
