### ISSUE TITLE
COMPLIANCE:  execute mais avec un su -

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#71]
```
# Exec: avec un if sur si on doit refaire ou pas et en su -
- name: Configure postgresql for the first time
  shell: initdb /var/lib/pgsql/data > /var/lib/pgsql/initdb.log
  args:
    creates: /var/lib/pgsql/initdb.log
  become: true
  become_user: postgres
```
