### ISSUE TITLE
COMPLIANCE: edition partielle avec remplacement de ligne

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#72]
```
# Edition partielle avec remplacement de ligne
- name: Allow localhost connection on postgresql
  lineinfile: 
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: "host    all             all             127.0.0.1/32"
    line: "host    all             all             127.0.0.1/32            md5"
    backrefs: yes
```
