### ISSUE TITLE
COMPLIANCE: gestion des service (avec état)

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#73]
```
# Gestion des services (avec état)
- name: Start and enable postgresql service
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: postgresql
```
