### ISSUE TITLE
COMPLIANCE: postgre: création uer & bdd

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#74]
```
# Postgres Création de user avec password
- name: Create xwiki postgreSQL user
  postgresql_user: 
    name: xwiki
    password: "{{ xwiki_password }}"

# Création de badd postgresql
- name: Create xwiki postgreSQL database
  postgresql_db:
    name: xwiki
    owner: xwiki
    encoding: unicode
```
