### ISSUE TITLE
COMPLIANCE: création user & group

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#75]
```
# Creation d'un groupe
- name: Create tomcat group
  group: 
    name: tomcat8

# Création d'un user dans un group + shell + home
- name: Create tomcat user
  user:
    name: tomcat8
    group: tomcat8
    shell: /bin/false 
    home: /home/tomcat8
```
