### ISSUE TITLE
COMPLIANCE: get uri HTTPS mais avec check certificat ou pas

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#76]
```
# Get URI (avec cert ou pas) & untar
- name: Get tomcat dist from apache website
  unarchive:
    src: http://apache.mirrors.ovh.net/ftp.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
    validate_certs: false
    dest: /var/lib
    remote_src: yes
```
