### ISSUE TITLE
COMPLIANCE: créer un répertoire (avec recursion) & droits

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#77]
```
# Change le droit d'un répertoire (avec récursion)
- name: Change owner
  file: 
    path: /var/lib/apache-tomcat-{{ tomcat_version }}
    owner: tomcat8
    group: tomcat8
    recurse: yes
    state: directory
```
