### ISSUE TITLE
COMPLIANCE: création lien symbolique

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#78]
```

# Creation d'un lien symbolique
- name: Create link for tomcat
  file: 
    src: /var/lib/apache-tomcat-{{ tomcat_version }}
    dest: "{{ tomcat8_path }}"
    state: link
```
