### ISSUE TITLE
COMPLIANCE: suppression de répertoire

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#79]
```
# RM répertoire
# WHEN?
- name: Clean ROOT directories in tomcat (default applications)
  file:
    path: "{{ tomcat8_path }}/webapps/ROOT"
    state: absent
  when: clean_tomcat_ROOT
```
