### ISSUE TITLE
COMPLIANCE: copy fichier

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#80]
```
# Génération d'un fichier à partir d'un tpl
- name: Copy unit file
  template: 
    src: tomcat8.service.j2
    dest: /etc/systemd/system/tomcat8.service
```
