### ISSUE TITLE
COMPLIANCE: partial avec insertion APRES

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#81]
```
# Partial avec insersion APRES
- name: UTF-8 URI encoding
  lineinfile: 
    path: "{{ tomcat8_path }}/conf/server.xml"
    state: present
    line: '               URIEncoding="UTF-8"'
    insertafter: "<Connector port=\"8080\" protocol=\"HTTP/1.1\""
```
