### ISSUE TITLE
COMPLIANCE: partial avec juste une ligne

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#82]
```

# Partial avec juste une ligne
- name: add setenv.sh to configure Xmx and ALLOW_ENCODED_SLASH
  lineinfile:
    path: "{{ tomcat8_path }}/bin/setenv.sh"
    create: yes
    line: CATALINA_OPTS="-Xmx1024m -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true"

```
