### ISSUE TITLE
COMPLIANCE: rajout de lignes en duplicate foreach

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#83]
```
# Rajout de lignes avec un duplicate for each
- name: Add a few lines in xwiki.cfg file
  lineinfile: 
    dest: "{{ tomcat8_path }}/webapps/{{ xwiki_path }}/WEB-INF/xwiki.cfg"
    line: "{{ item }}"
  with_items:
    - "xwiki.stats=1"
    - "xwiki.store.attachment.hint = file"
    - "xwiki.store.attachment.versioning.hint = file"
    - "xwiki.store.attachment.recyclebin.hint = file"
    - "xwiki.data.dir = {{ tomcat8_path }}/work"
```
