### ISSUE TITLE
COMPLIANCE: repository avec déclaration de clé

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#85]
```
# Repository add avec déclaration de clé
- name: Add elasticsearch repository
  yum_repository:
    name: elasticsearch-5.x
    description: elasticsearch repository for 5.x packages
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
```
