### ISSUE TITLE
COMPLIANCE: rajout de clé dans RPM

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#86]
```
# Rajout de la clé, utile?
- name: Add Elasticsearch key to keystore
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
```
