### ISSUE TITLE
COMPLIANCE: check que paquet à la dernière version

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#87]
```
# Check that the version is the latest
- name: Install Filebeat
  yum:
    name: filebeat
    state: latest
```
