### ISSUE TITLE
COMPLIANCE: gestion du notify

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#88]
```

# NOTIFY?
- name: Configure metricbeat to collect docker stats
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
  notify: "notify metricbeat for restart"
```
