### ISSUE TITLE
COMPLIANCE: gestion du delegate

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#89]
```

# delegate?
- name: Configure filebeat log collection in central logstash
  template: 
    src: nginx.conf.j2
    dest: /etc/logstash/conf.d/{{inventory_hostname}}_nginx.conf
  notify: "notify logstash for restart"
  delegate_to: '{{elk_server}}'
```
